<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>1.0.$([System.DateTime]::Now.ToString("yyyy")).$([System.DateTime]::Now.ToString("MMdd"))</Version>
    <FileVersion>1.0.$([System.DateTime]::Now.ToString("yyyy")).$([System.DateTime]::Now.ToString("MMdd"))</FileVersion>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>admanager.ico</ApplicationIcon>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
    <ForceDesignerDpiUnaware>true</ForceDesignerDpiUnaware>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.DirectoryServices" Version="8.0.0" />
    <PackageReference Include="System.DirectoryServices.AccountManagement" Version="8.0.0" />
  </ItemGroup>
</Project>