// <auto-generated/>
#nullable enable
using System.Drawing;
using System.Windows.Forms;

namespace ADManager.Dialogs;

partial class AdminCredentialsDialog
{
    private System.ComponentModel.IContainer? components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    private Button _btnOk     = null!;
    private Button _btnCancel = null!;

    private void InitializeComponent()
    {
        this.Text            = "Требуются права администратора";
        this.Size            = new System.Drawing.Size(360, 200);
        this.FormBorderStyle = FormBorderStyle.FixedDialog;
        this.StartPosition   = FormStartPosition.CenterParent;
        this.MaximizeBox     = false;
        this.MinimizeBox     = false;
        this.Font            = new System.Drawing.Font("Segoe UI", 9.5f);
        this.BackColor       = System.Drawing.Color.FromArgb(240, 242, 245);
        this.AutoScaleMode   = AutoScaleMode.Font;

        SuspendLayout();

        var lblUser = new Label();
        lblUser.Text     = "Логин (domain\\user или UPN):";
        lblUser.Location = new System.Drawing.Point(10, 15);
        lblUser.Size     = new System.Drawing.Size(330, 18);

        _txtUser = new TextBox();
        _txtUser.Location = new System.Drawing.Point(10, 35);
        _txtUser.Size     = new System.Drawing.Size(330, 22);

        var lblPwd = new Label();
        lblPwd.Text     = "Пароль:";
        lblPwd.Location = new System.Drawing.Point(10, 65);
        lblPwd.Size     = new System.Drawing.Size(330, 18);

        _txtPwd = new TextBox();
        _txtPwd.Location              = new System.Drawing.Point(10, 85);
        _txtPwd.Size                  = new System.Drawing.Size(330, 22);
        _txtPwd.UseSystemPasswordChar = true;

        _btnOk = new Button();
        _btnOk.Text         = "OK";
        _btnOk.Location     = new System.Drawing.Point(170, 120);
        _btnOk.Size         = new System.Drawing.Size(80, 28);
        _btnOk.DialogResult = DialogResult.OK;
        _btnOk.BackColor    = System.Drawing.Color.FromArgb(50, 55, 70);
        _btnOk.ForeColor    = System.Drawing.Color.White;
        _btnOk.FlatStyle    = FlatStyle.Flat;
        _btnOk.FlatAppearance.BorderSize = 0;

        _btnCancel = new Button();
        _btnCancel.Text         = "Отмена";
        _btnCancel.Location     = new System.Drawing.Point(260, 120);
        _btnCancel.Size         = new System.Drawing.Size(80, 28);
        _btnCancel.DialogResult = DialogResult.Cancel;

        this.AcceptButton = _btnOk;
        this.CancelButton = _btnCancel;

        this.Controls.AddRange(new Control[] { lblUser, _txtUser, lblPwd, _txtPwd, _btnOk, _btnCancel });

        ResumeLayout(false);
    }
}
