// <auto-generated/>
#nullable enable
using System.Drawing;
using System.Windows.Forms;

namespace ADManager.Dialogs;

partial class ChangePasswordDialog
{
    private System.ComponentModel.IContainer? components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        this.Text            = "Смена пароля";
        this.Size            = new System.Drawing.Size(820, 500);
        this.FormBorderStyle = FormBorderStyle.FixedDialog;
        this.StartPosition   = FormStartPosition.CenterParent;
        this.MaximizeBox     = false;
        this.MinimizeBox     = false;
        this.Font            = new System.Drawing.Font("Segoe UI", 9.5f);
        this.BackColor       = System.Drawing.Color.FromArgb(240, 242, 245);
        this.AutoScaleMode   = AutoScaleMode.Font;

        SuspendLayout();

        // ── Левая панель ──────────────────────────────────────────
        var leftPanel = new Panel();
        leftPanel.Location = new System.Drawing.Point(10, 10);
        leftPanel.Size     = new System.Drawing.Size(370, 370);

        var lblNewPwd = new Label();
        lblNewPwd.Text     = "Новый пароль:";
        lblNewPwd.Location = new System.Drawing.Point(0, 5);
        lblNewPwd.Size     = new System.Drawing.Size(360, 18);

        _txtNewPwd = new TextBox();
        _txtNewPwd.Location              = new System.Drawing.Point(0, 25);
        _txtNewPwd.Size                  = new System.Drawing.Size(360, 24);
        _txtNewPwd.UseSystemPasswordChar = true;
        _txtNewPwd.Font                  = new System.Drawing.Font("Consolas", 10f);

        var lblConfirm = new Label();
        lblConfirm.Text     = "Подтверждение пароля:";
        lblConfirm.Location = new System.Drawing.Point(0, 58);
        lblConfirm.Size     = new System.Drawing.Size(360, 18);

        _txtConfirm = new TextBox();
        _txtConfirm.Location              = new System.Drawing.Point(0, 78);
        _txtConfirm.Size                  = new System.Drawing.Size(360, 24);
        _txtConfirm.UseSystemPasswordChar = true;
        _txtConfirm.Font                  = new System.Drawing.Font("Consolas", 10f);

        var chkShow = new CheckBox();
        chkShow.Text     = "Показать пароль";
        chkShow.Location = new System.Drawing.Point(0, 108);
        chkShow.Size     = new System.Drawing.Size(200, 22);

        _lblMatch = new Label();
        _lblMatch.Location = new System.Drawing.Point(210, 108);
        _lblMatch.Size     = new System.Drawing.Size(150, 22);
        _lblMatch.Font     = new System.Drawing.Font("Segoe UI", 9.5f, System.Drawing.FontStyle.Bold);

        _chkMustChange = new CheckBox();
        _chkMustChange.Text     = "Требовать смены пароля при следующем входе";
        _chkMustChange.Location = new System.Drawing.Point(0, 138);
        _chkMustChange.Size     = new System.Drawing.Size(360, 22);

        var btnApply = new Button();
        btnApply.Text      = "Применить";
        btnApply.Location  = new System.Drawing.Point(0, 170);
        btnApply.Size      = new System.Drawing.Size(120, 32);
        btnApply.BackColor = System.Drawing.Color.FromArgb(50, 55, 70);
        btnApply.ForeColor = System.Drawing.Color.White;
        btnApply.FlatStyle = FlatStyle.Flat;
        btnApply.Font      = new System.Drawing.Font("Segoe UI", 9f, System.Drawing.FontStyle.Bold);
        btnApply.FlatAppearance.BorderSize = 0;

        var btnCancel = new Button();
        btnCancel.Text         = "Отмена";
        btnCancel.Location     = new System.Drawing.Point(130, 170);
        btnCancel.Size         = new System.Drawing.Size(100, 32);
        btnCancel.DialogResult = DialogResult.Cancel;

        _lblResult = new Label();
        _lblResult.Location = new System.Drawing.Point(0, 212);
        _lblResult.Size     = new System.Drawing.Size(360, 40);
        _lblResult.Font     = new System.Drawing.Font("Segoe UI", 9f);

        leftPanel.Controls.AddRange(new Control[]
        {
            lblNewPwd, _txtNewPwd, lblConfirm, _txtConfirm,
            chkShow, _lblMatch, _chkMustChange, btnApply, btnCancel, _lblResult
        });

        // ── Правая панель ─────────────────────────────────────────
        var rightPanel = new Panel();
        rightPanel.Location    = new System.Drawing.Point(390, 10);
        rightPanel.Size        = new System.Drawing.Size(400, 426);
        rightPanel.BorderStyle = BorderStyle.FixedSingle;
        rightPanel.BackColor   = System.Drawing.Color.White;

        var lblGenTitle = new Label();
        lblGenTitle.Text     = "Генератор паролей";
        lblGenTitle.Location = new System.Drawing.Point(5, 8);
        lblGenTitle.Size     = new System.Drawing.Size(380, 22);
        lblGenTitle.Font     = new System.Drawing.Font("Segoe UI", 10f, System.Drawing.FontStyle.Bold);

        var lblLenLabel = new Label();
        lblLenLabel.Text     = "Длина пароля:";
        lblLenLabel.Location = new System.Drawing.Point(5, 38);
        lblLenLabel.Size     = new System.Drawing.Size(110, 22);

        _numLength = new NumericUpDown();
        _numLength.Location = new System.Drawing.Point(120, 36);
        _numLength.Size     = new System.Drawing.Size(70, 22);
        _numLength.Minimum  = 4;
        _numLength.Maximum  = 256;
        _numLength.Value    = 12;

        _chkMemo = new CheckBox();
        _chkMemo.Text     = "Запоминающийся пароль";
        _chkMemo.Location = new System.Drawing.Point(5, 64);
        _chkMemo.Size     = new System.Drawing.Size(380, 22);

        _chkUpper = new CheckBox();
        _chkUpper.Text     = "Прописные буквы (A–Z)";
        _chkUpper.Location = new System.Drawing.Point(5, 116);
        _chkUpper.Size     = new System.Drawing.Size(380, 20);
        _chkUpper.Checked  = true;

        _chkLower = new CheckBox();
        _chkLower.Text     = "Строчные буквы (a–z)";
        _chkLower.Location = new System.Drawing.Point(5, 138);
        _chkLower.Size     = new System.Drawing.Size(380, 20);
        _chkLower.Checked  = true;

        _chkDigits = new CheckBox();
        _chkDigits.Text     = "Цифры (0–9)";
        _chkDigits.Location = new System.Drawing.Point(5, 160);
        _chkDigits.Size     = new System.Drawing.Size(380, 20);
        _chkDigits.Checked  = true;

        _chkSymbols = new CheckBox();
        _chkSymbols.Text     = "Символы !\"№;%:?*()_+";
        _chkSymbols.Location = new System.Drawing.Point(5, 182);
        _chkSymbols.Size     = new System.Drawing.Size(380, 20);

        _chkNoRepeat = new CheckBox();
        _chkNoRepeat.Text     = "Избегать повторения символов";
        _chkNoRepeat.Location = new System.Drawing.Point(5, 204);
        _chkNoRepeat.Size     = new System.Drawing.Size(380, 20);

        var btnGenerate = new Button();
        btnGenerate.Text      = "Сгенерировать 5 вариантов";
        btnGenerate.Location  = new System.Drawing.Point(5, 230);
        btnGenerate.Size      = new System.Drawing.Size(385, 30);
        btnGenerate.BackColor = System.Drawing.Color.FromArgb(34, 139, 75);
        btnGenerate.ForeColor = System.Drawing.Color.White;
        btnGenerate.FlatStyle = FlatStyle.Flat;
        btnGenerate.Font      = new System.Drawing.Font("Segoe UI", 9f, System.Drawing.FontStyle.Bold);
        btnGenerate.FlatAppearance.BorderSize = 0;

        _genButtons = new Button[5];

        rightPanel.Controls.AddRange(new Control[]
        {
            lblGenTitle, lblLenLabel, _numLength,
            _chkMemo, _chkUpper, _chkLower, _chkDigits, _chkSymbols, _chkNoRepeat,
            btnGenerate
        });

        this.CancelButton = btnCancel;
        this.Controls.Add(leftPanel);
        this.Controls.Add(rightPanel);

        ResumeLayout(false);
    }
}
