// <auto-generated/>
#nullable enable
using System.Drawing;
using System.Windows.Forms;

namespace ADManager.Dialogs;

partial class SetExpiryDialog
{
    private System.ComponentModel.IContainer? components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        this.Text            = "Срок действия учётной записи";
        this.FormBorderStyle = FormBorderStyle.FixedDialog;
        this.StartPosition   = FormStartPosition.CenterParent;
        this.MaximizeBox     = false;
        this.MinimizeBox     = false;
        this.Font            = new System.Drawing.Font("Segoe UI", 9.5f);
        this.BackColor       = System.Drawing.Color.FromArgb(240, 242, 245);
        this.ClientSize      = new System.Drawing.Size(460, 212);
        this.AutoScaleMode   = AutoScaleMode.Font;

        SuspendLayout();

        var lblName = new Label();
        lblName.Text      = "Пользователь";
        lblName.Location  = new System.Drawing.Point(12, 10);
        lblName.AutoSize  = true;
        lblName.Font      = new System.Drawing.Font("Segoe UI", 11f, System.Drawing.FontStyle.Bold);
        lblName.ForeColor = System.Drawing.Color.FromArgb(30, 60, 130);

        var sep = new Panel();
        sep.Location  = new System.Drawing.Point(8, 58);
        sep.Size      = new System.Drawing.Size(444, 1);
        sep.BackColor = System.Drawing.Color.FromArgb(190, 195, 210);

        _rdoNever = new RadioButton();
        _rdoNever.Text     = "Никогда";
        _rdoNever.Location = new System.Drawing.Point(12, 70);
        _rdoNever.AutoSize = true;
        _rdoNever.Checked  = true;

        _rdoExpires = new RadioButton();
        _rdoExpires.Text     = "Истекает:";
        _rdoExpires.Location = new System.Drawing.Point(12, 100);
        _rdoExpires.AutoSize = true;

        _dtp = new DateTimePicker();
        _dtp.Location = new System.Drawing.Point(112, 97);
        _dtp.Size     = new System.Drawing.Size(330, 24);
        _dtp.Format   = DateTimePickerFormat.Long;
        _dtp.Enabled  = false;

        var btnApply = new Button();
        btnApply.Text      = "Применить";
        btnApply.Location  = new System.Drawing.Point(238, 162);
        btnApply.Size      = new System.Drawing.Size(110, 32);
        btnApply.BackColor = System.Drawing.Color.FromArgb(50, 100, 200);
        btnApply.ForeColor = System.Drawing.Color.White;
        btnApply.FlatStyle = FlatStyle.Flat;
        btnApply.Font      = new System.Drawing.Font("Segoe UI", 9f, System.Drawing.FontStyle.Bold);
        btnApply.FlatAppearance.BorderSize = 0;

        var btnCancel = new Button();
        btnCancel.Text         = "Отмена";
        btnCancel.Location     = new System.Drawing.Point(358, 162);
        btnCancel.Size         = new System.Drawing.Size(90, 32);
        btnCancel.DialogResult = DialogResult.Cancel;
        btnCancel.FlatStyle    = FlatStyle.Flat;
        btnCancel.FlatAppearance.BorderSize = 0;

        this.AcceptButton = btnApply;
        this.CancelButton = btnCancel;

        this.Controls.AddRange(new Control[]
        {
            lblName, sep,
            _rdoNever, _rdoExpires, _dtp,
            btnApply, btnCancel
        });

        ResumeLayout(false);
    }
}
