// <auto-generated/>
#nullable enable
using System.Drawing;
using System.Windows.Forms;

namespace ADManager.Dialogs;

partial class UserDetailsDialog
{
    private System.ComponentModel.IContainer? components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        this.Text            = "Информация о пользователе";
        this.FormBorderStyle = FormBorderStyle.FixedDialog;
        this.StartPosition   = FormStartPosition.CenterParent;
        this.MaximizeBox     = false;
        this.MinimizeBox     = false;
        this.Font            = new System.Drawing.Font("Segoe UI", 9.5f);
        this.BackColor       = System.Drawing.Color.FromArgb(240, 242, 245);
        this.ClientSize      = new System.Drawing.Size(580, 500);
        this.AutoScaleMode   = AutoScaleMode.Font;

        SuspendLayout();

        var lblHint = new Label();
        lblHint.Text      = "Содержимое заполняется при открытии из AD";
        lblHint.Location  = new System.Drawing.Point(10, 10);
        lblHint.AutoSize  = true;
        lblHint.ForeColor = System.Drawing.Color.FromArgb(100, 110, 130);
        lblHint.Font      = new System.Drawing.Font("Segoe UI", 9f, System.Drawing.FontStyle.Italic);

        var btnClose = new Button();
        btnClose.Text         = "Закрыть";
        btnClose.Size         = new System.Drawing.Size(100, 30);
        btnClose.Location     = new System.Drawing.Point(240, 450);
        btnClose.DialogResult = DialogResult.OK;
        btnClose.BackColor    = System.Drawing.Color.FromArgb(50, 55, 70);
        btnClose.ForeColor    = System.Drawing.Color.White;
        btnClose.FlatStyle    = FlatStyle.Flat;
        btnClose.FlatAppearance.BorderSize = 0;

        this.AcceptButton = btnClose;
        this.Controls.AddRange(new Control[] { lblHint, btnClose });

        ResumeLayout(false);
    }
}
