// <auto-generated/>
#nullable enable
using System.Drawing;
using System.Windows.Forms;
using ADManager.Helpers;

namespace ADManager.Tabs;

partial class Tab1_UserSearch
{
    private System.ComponentModel.IContainer? components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    private DataGridView?       _grid;
    private Button?             _btnUnlock;
    private Button?             _btnChangePwd;
    private Label?              _lblSelectedUser;
    private Label?              _lblDisabledStatus;

    // Дополнительные поля для WireEvents
    private TextBox             _txtSn        = null!;
    private TextBox             _txtGn        = null!;
    private Button              _btnSearch     = null!;
    private ContextMenuStrip    _ctxMenu       = null!;
    private ToolStripMenuItem   _menuGroups    = null!;
    private ToolStripMenuItem   _menuDetails   = null!;
    private ToolStripMenuItem   _menuExpiry    = null!;
    private ToolStripMenuItem   _menuUnlock    = null!;
    private ToolStripMenuItem   _menuLock      = null!;
    private ToolStripMenuItem   _menuEnable    = null!;
    private ToolStripMenuItem   _menuDisable   = null!;

    private void InitializeComponent()
    {
        this.Size          = new System.Drawing.Size(1200, 680);
        this.AutoScaleMode = AutoScaleMode.Font;
        BackColor = Color.FromArgb(240, 242, 245);
        SuspendLayout();

        // ── Поля ввода ──────────────────────────────────────────
        var lblSn = UiFactory.MakeLabel("Фамилия (обязательно):");
        lblSn.Location = new Point(8, 6);

        _txtSn = UiFactory.MakeTextBox("Напр.: Иванов", 200);
        _txtSn.Location = new Point(8, 26);

        var lblGn = UiFactory.MakeLabel("Имя (необязательно):");
        lblGn.Location = new Point(218, 6);

        _txtGn = UiFactory.MakeTextBox("Напр.: Иван", 180);
        _txtGn.Location = new Point(218, 26);

        // ── Кнопки ──────────────────────────────────────────────
        _btnSearch = UiFactory.MakeActionButton("Найти", 100);
        _btnSearch.Location = new Point(408, 24);

        _btnUnlock = UiFactory.MakeActionButton("Разблокировать", 140);
        _btnUnlock.Location   = new Point(514, 24);
        _btnUnlock.Enabled    = false;
        _btnUnlock.BackColor  = Color.FromArgb(120, 125, 140);

        _btnChangePwd = UiFactory.MakeActionButton("Сменить пароль", 140);
        _btnChangePwd.Location  = new Point(660, 24);
        _btnChangePwd.Enabled   = false;
        _btnChangePwd.BackColor = Color.FromArgb(120, 125, 140);

        _lblSelectedUser = new Label();
        _lblSelectedUser.Location  = new Point(808, 28);
        _lblSelectedUser.Size      = new Size(180, 22);
        _lblSelectedUser.ForeColor = Color.FromArgb(50, 80, 160);
        _lblSelectedUser.Font      = new Font("Segoe UI", 9f, FontStyle.Bold);

        _lblDisabledStatus = new Label();
        _lblDisabledStatus.Location  = new Point(995, 28);
        _lblDisabledStatus.Size      = new Size(100, 22);
        _lblDisabledStatus.Text      = "Отключена!";
        _lblDisabledStatus.ForeColor = Color.FromArgb(220, 60, 60);
        _lblDisabledStatus.Font      = new Font("Segoe UI", 9f, FontStyle.Bold);
        _lblDisabledStatus.Visible   = false;

        // ── DataGridView ─────────────────────────────────────────
        _grid = UiFactory.MakeGrid();
        _grid.Location = new Point(5, 58);
        _grid.Size     = new System.Drawing.Size(1190, 617);
        _grid.Anchor   = AnchorStyles.Top | AnchorStyles.Left |
                         AnchorStyles.Right | AnchorStyles.Bottom;

        // ── Контекстное меню ─────────────────────────────────────
        _ctxMenu      = new ContextMenuStrip();
        _menuGroups   = new ToolStripMenuItem("👥  Группы пользователя");
        _menuDetails  = new ToolStripMenuItem("ℹ  Подробная информация");
        var menuSep1  = new ToolStripSeparator();
        _menuExpiry   = new ToolStripMenuItem("📅  Установить срок действия");
        var menuSep2  = new ToolStripSeparator();
        _menuUnlock   = new ToolStripMenuItem("🔓  Разблокировать");
        _menuLock     = new ToolStripMenuItem("🔒  Заблокировать");
        _menuEnable   = new ToolStripMenuItem("✅  Включить");
        _menuDisable  = new ToolStripMenuItem("🚫  Отключить");
        _ctxMenu.Items.AddRange(new ToolStripItem[]
        {
            _menuGroups, _menuDetails,
            menuSep1, _menuExpiry,
            menuSep2, _menuUnlock, _menuLock, _menuEnable, _menuDisable
        });
        _grid.ContextMenuStrip = _ctxMenu;

        Controls.AddRange(new Control[]
        {
            lblSn, _txtSn, lblGn, _txtGn,
            _btnSearch, _btnUnlock, _btnChangePwd,
            _lblSelectedUser, _lblDisabledStatus, _grid
        });

        ResumeLayout(false);
    }
}
