// <auto-generated/>
#nullable enable
using System.Drawing;
using System.Windows.Forms;
using ADManager.Helpers;

namespace ADManager.Tabs;

partial class Tab2_Groups
{
    private System.ComponentModel.IContainer? components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    private Button _btnSearch     = null!;
    private Button _btnEditGroups = null!;

    private void InitializeComponent()
    {
        this.Size          = new System.Drawing.Size(1200, 680);
        this.AutoScaleMode = AutoScaleMode.Font;
        BackColor = Color.FromArgb(240, 242, 245);
        SuspendLayout();

        var lblSam = UiFactory.MakeLabel("Логин:");
        lblSam.Location = new Point(8, 6);

        _txtSam = UiFactory.MakeTextBox("Напр.: i.ivanov", 200);
        _txtSam.Location = new Point(8, 26);

        var lblDomain = UiFactory.MakeLabel("Домен:");
        lblDomain.Location = new Point(218, 6);

        _cbDomain = UiFactory.MakeComboBox(MainForm.Domains, 0, 200);
        _cbDomain.Location = new Point(218, 26);

        _btnSearch = UiFactory.MakeActionButton("Показать группы", 150);
        _btnSearch.Location = new Point(424, 24);

        _btnEditGroups = new Button
        {
            Text      = "Редактировать группы",
            Size      = new Size(170, 28),
            Location  = new Point(582, 24),
            BackColor = Color.FromArgb(50, 100, 200),
            ForeColor = Color.White,
            FlatStyle = FlatStyle.Flat,
            Font      = new Font("Segoe UI", 9f, FontStyle.Bold)
        };
        _btnEditGroups.FlatAppearance.BorderSize = 0;

        _grid = UiFactory.MakeGrid();
        _grid.Location = new Point(5, 58);
        _grid.Size     = new System.Drawing.Size(1190, 617);
        _grid.Anchor   = AnchorStyles.Top | AnchorStyles.Left |
                         AnchorStyles.Right | AnchorStyles.Bottom;

        Controls.AddRange(new Control[]
        {
            lblSam, _txtSam, lblDomain, _cbDomain, _btnSearch, _btnEditGroups, _grid
        });

        ResumeLayout(false);
    }
}
