// <auto-generated/>
#nullable enable
using System.Drawing;
using System.Windows.Forms;
using ADManager.Helpers;

namespace ADManager.Tabs;

partial class Tab3_Passwords
{
    private System.ComponentModel.IContainer? components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    private Button _btnSearch = null!;
    private Button _btnExport = null!;

    private void InitializeComponent()
    {
        this.Size          = new System.Drawing.Size(1200, 680);
        this.AutoScaleMode = AutoScaleMode.Font;
        BackColor = Color.FromArgb(240, 242, 245);
        SuspendLayout();

        var pan = new Panel();
        pan.Location    = new Point(5, 5);
        pan.Size        = new Size(980, 44);
        pan.BackColor   = Color.FromArgb(230, 232, 238);
        pan.BorderStyle = BorderStyle.FixedSingle;

        _rdExpired = new RadioButton();
        _rdExpired.Text     = "Уже истёкшие пароли";
        _rdExpired.Location = new Point(8, 12);
        _rdExpired.Size     = new Size(200, 22);
        _rdExpired.Checked  = true;

        _rdExpireSoon = new RadioButton();
        _rdExpireSoon.Text     = "Истекают в ближайшие";
        _rdExpireSoon.Location = new Point(215, 12);
        _rdExpireSoon.Size     = new Size(190, 22);

        _numDays = new NumericUpDown();
        _numDays.Location = new Point(410, 10);
        _numDays.Size     = new Size(60, 22);
        _numDays.Minimum  = 1;
        _numDays.Maximum  = 30;
        _numDays.Value    = 5;

        var lblDays = new Label();
        lblDays.Text     = "дней";
        lblDays.Location = new Point(476, 13);
        lblDays.AutoSize = true;

        _btnSearch = UiFactory.MakeActionButton("Найти", 100);
        _btnSearch.Location = new Point(520, 9);

        _btnExport = UiFactory.MakeExportButton();
        _btnExport.Location = new Point(626, 9);

        pan.Controls.AddRange(new Control[]
        {
            _rdExpired, _rdExpireSoon, _numDays, lblDays, _btnSearch, _btnExport
        });

        _grid = UiFactory.MakeGrid();
        _grid.Location = new Point(5, 58);
        _grid.Size     = new System.Drawing.Size(1190, 617);
        _grid.Anchor   = AnchorStyles.Top | AnchorStyles.Left |
                         AnchorStyles.Right | AnchorStyles.Bottom;

        Controls.AddRange(new Control[] { pan, _grid });

        ResumeLayout(false);
    }
}
