// <auto-generated/>
#nullable enable
using System.Drawing;
using System.Windows.Forms;
using ADManager.Helpers;

namespace ADManager.Tabs;

partial class Tab4_Activity
{
    private System.ComponentModel.IContainer? components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    private Button _btnSearch = null!;
    private Button _btnExport = null!;

    private void InitializeComponent()
    {
        this.Size          = new System.Drawing.Size(1200, 680);
        this.AutoScaleMode = AutoScaleMode.Font;
        BackColor = Color.FromArgb(240, 242, 245);
        SuspendLayout();

        var pan = new Panel();
        pan.Location    = new Point(5, 5);
        pan.Size        = new Size(980, 70);
        pan.BackColor   = Color.FromArgb(230, 232, 238);
        pan.BorderStyle = BorderStyle.FixedSingle;

        var lblPre = new Label();
        lblPre.Text     = "Последний вход более";
        lblPre.Location = new Point(8, 13);
        lblPre.AutoSize = true;

        _numDays = new NumericUpDown();
        _numDays.Location = new Point(160, 10);
        _numDays.Size     = new Size(70, 22);
        _numDays.Minimum  = 1;
        _numDays.Maximum  = 3650;
        _numDays.Value    = 90;

        var lblPost = new Label();
        lblPost.Text     = "дней назад";
        lblPost.Location = new Point(235, 13);
        lblPost.AutoSize = true;

        _chkMustChange = new CheckBox();
        _chkMustChange.Text     = "Только с флагом \"Сменить пароль при входе\"";
        _chkMustChange.Location = new Point(320, 12);
        _chkMustChange.Size     = new Size(320, 22);

        _btnSearch = UiFactory.MakeActionButton("Найти", 100);
        _btnSearch.Location = new Point(648, 9);

        _btnExport = UiFactory.MakeExportButton();
        _btnExport.Location = new Point(754, 9);

        var lblType = new Label();
        lblType.Text     = "Тип объекта:";
        lblType.Location = new Point(8, 44);
        lblType.AutoSize = true;

        _rdAll = new RadioButton();
        _rdAll.Text     = "Все УЗ";
        _rdAll.Location = new Point(100, 42);
        _rdAll.Size     = new Size(90, 22);
        _rdAll.Checked  = true;

        _rdUsers = new RadioButton();
        _rdUsers.Text     = "Только пользователи";
        _rdUsers.Location = new Point(196, 42);
        _rdUsers.Size     = new Size(160, 22);

        _rdComputers = new RadioButton();
        _rdComputers.Text     = "Только устройства";
        _rdComputers.Location = new Point(362, 42);
        _rdComputers.Size     = new Size(150, 22);

        pan.Controls.AddRange(new Control[]
        {
            lblPre, _numDays, lblPost, _chkMustChange, _btnSearch, _btnExport,
            lblType, _rdAll, _rdUsers, _rdComputers
        });

        _grid = UiFactory.MakeGrid();
        _grid.Location = new Point(5, 84);
        _grid.Size     = new System.Drawing.Size(1190, 591);
        _grid.Anchor   = AnchorStyles.Top | AnchorStyles.Left |
                         AnchorStyles.Right | AnchorStyles.Bottom;

        Controls.AddRange(new Control[] { pan, _grid });

        ResumeLayout(false);
    }
}
