// <auto-generated/>
#nullable enable
using System.Drawing;
using System.Windows.Forms;
using ADManager.Helpers;

namespace ADManager.Tabs;

partial class Tab5_Duplicates
{
    private System.ComponentModel.IContainer? components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    private Button _btnFind   = null!;
    private Button _btnExport = null!;

    private void InitializeComponent()
    {
        this.Size          = new System.Drawing.Size(1200, 680);
        this.AutoScaleMode = AutoScaleMode.Font;
        BackColor = Color.FromArgb(240, 242, 245);
        SuspendLayout();

        var pan = new Panel();
        pan.Location    = new Point(5, 5);
        pan.Size        = new Size(980, 50);
        pan.BackColor   = Color.FromArgb(230, 232, 238);
        pan.BorderStyle = BorderStyle.FixedSingle;

        var lblDesc = new Label();
        lblDesc.Text      = "Поиск дублирующихся и похожих УЗ среди активных УЗ по всем доменам (по DisplayName и фамилии)";
        lblDesc.Location  = new Point(8, 8);
        lblDesc.Size      = new Size(680, 18);
        lblDesc.ForeColor = Color.FromArgb(60, 70, 100);

        _chkExact = new CheckBox();
        _chkExact.Text     = "Только точные совпадения";
        _chkExact.Location = new Point(8, 27);
        _chkExact.Size     = new Size(220, 20);

        _btnFind = UiFactory.MakeActionButton("Найти дубликаты", 150);
        _btnFind.Location = new Point(700, 11);

        _btnExport = UiFactory.MakeExportButton();
        _btnExport.Location = new Point(856, 11);

        pan.Controls.AddRange(new Control[] { lblDesc, _chkExact, _btnFind, _btnExport });

        _grid = UiFactory.MakeGrid();
        _grid.Location = new Point(5, 60);
        _grid.Size     = new System.Drawing.Size(1190, 615);
        _grid.Anchor   = AnchorStyles.Top | AnchorStyles.Left |
                         AnchorStyles.Right | AnchorStyles.Bottom;

        Controls.AddRange(new Control[] { pan, _grid });

        ResumeLayout(false);
    }
}
