// <auto-generated/>
#nullable enable
using System.Drawing;
using System.Windows.Forms;
using ADManager.Helpers;

namespace ADManager.Tabs;

partial class Tab6_SearchByList
{
    private System.ComponentModel.IContainer? components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    private Button _btnLoadFile  = null!;
    private Button _btnClearList = null!;
    private Button _btnFind      = null!;
    private Button _btnExport    = null!;
    private Button _btnClear     = null!;

    private void InitializeComponent()
    {
        this.Size          = new System.Drawing.Size(1200, 680);
        this.AutoScaleMode = AutoScaleMode.Font;
        BackColor = Color.FromArgb(240, 242, 245);
        SuspendLayout();

        // ── Домены ──────────────────────────────────────────────
        var lblDomains = UiFactory.MakeLabel("Домены:");
        lblDomains.Location = new Point(8, 6);

        _clbDomains = new CheckedListBox();
        _clbDomains.Location     = new Point(8, 26);
        _clbDomains.Size         = new Size(200, 100);
        _clbDomains.CheckOnClick = true;

        // ── Список ФИО ──────────────────────────────────────────
        var lblFio = UiFactory.MakeLabel("Список ФИО (каждое с новой строки):");
        lblFio.Location = new Point(220, 6);

        _txtFio = new TextBox();
        _txtFio.Location   = new Point(220, 26);
        _txtFio.Size       = new Size(380, 100);
        _txtFio.Multiline  = true;
        _txtFio.ScrollBars = ScrollBars.Vertical;
        _txtFio.Font       = new Font("Segoe UI", 9f);

        _btnLoadFile = new Button();
        _btnLoadFile.Text      = "Загрузить из файла";
        _btnLoadFile.Location  = new Point(610, 26);
        _btnLoadFile.Size      = new Size(150, 28);
        _btnLoadFile.BackColor = Color.FromArgb(100, 100, 200);
        _btnLoadFile.ForeColor = Color.White;
        _btnLoadFile.FlatStyle = FlatStyle.Flat;
        _btnLoadFile.FlatAppearance.BorderSize = 0;

        _btnClearList = new Button();
        _btnClearList.Text      = "Очистить список";
        _btnClearList.Location  = new Point(610, 62);
        _btnClearList.Size      = new Size(150, 28);
        _btnClearList.FlatStyle = FlatStyle.Flat;

        // ── Фильтры ──────────────────────────────────────────────
        var panFilters = new Panel();
        panFilters.Location    = new Point(5, 135);
        panFilters.Size        = new Size(980, 30);
        panFilters.BackColor   = Color.FromArgb(230, 232, 238);
        panFilters.BorderStyle = BorderStyle.FixedSingle;

        var lblFHead = new Label();
        lblFHead.Text     = "Фильтры поиска:";
        lblFHead.Location = new Point(5, 7);
        lblFHead.AutoSize = true;
        lblFHead.Font     = new Font("Segoe UI", 8.5f);

        _chkActiveOnly = new CheckBox();
        _chkActiveOnly.Text      = "Только активные УЗ";
        _chkActiveOnly.Location  = new Point(120, 6);
        _chkActiveOnly.Size      = new Size(160, 22);
        _chkActiveOnly.Checked   = true;
        _chkActiveOnly.ForeColor = Color.FromArgb(30, 120, 50);

        _chkNoPrefix = new CheckBox();
        _chkNoPrefix.Text     = "Без префиксов";
        _chkNoPrefix.Location = new Point(290, 6);
        _chkNoPrefix.Size     = new Size(130, 22);

        _chkExtPrefix = new CheckBox();
        _chkExtPrefix.Text     = "С префиксом ext_";
        _chkExtPrefix.Location = new Point(430, 6);
        _chkExtPrefix.Size     = new Size(150, 22);

        panFilters.Controls.AddRange(new Control[] { lblFHead, _chkActiveOnly, _chkNoPrefix, _chkExtPrefix });

        // ── Поля для выгрузки (структура создаётся в WireEvents) ─
        var panFields = new Panel();
        panFields.Location    = new Point(5, 170);
        panFields.Size        = new Size(980, 56);
        panFields.BackColor   = Color.FromArgb(230, 232, 238);
        panFields.BorderStyle = BorderStyle.FixedSingle;

        var lblFlds = new Label();
        lblFlds.Text     = "Поля для выгрузки:";
        lblFlds.Location = new Point(5, 9);
        lblFlds.AutoSize = true;
        lblFlds.Font     = new Font("Segoe UI", 8.5f);

        panFields.Controls.Add(lblFlds);
        _panFields = panFields;

        // ── Кнопки ───────────────────────────────────────────────
        _btnFind = UiFactory.MakeActionButton("Найти", 100);
        _btnFind.Location = new Point(5, 254);

        _btnExport = UiFactory.MakeExportButton();
        _btnExport.Location = new Point(115, 254);

        _btnClear = new Button();
        _btnClear.Text      = "Очистить таблицу";
        _btnClear.Location  = new Point(265, 254);
        _btnClear.Size      = new Size(140, 28);
        _btnClear.FlatStyle = FlatStyle.Flat;

        _lblCount = new Label();
        _lblCount.Location  = new Point(420, 258);
        _lblCount.AutoSize  = true;
        _lblCount.ForeColor = Color.FromArgb(50, 100, 200);
        _lblCount.Font      = new Font("Segoe UI", 9f, FontStyle.Bold);

        _grid = UiFactory.MakeGrid();
        _grid.Location = new Point(5, 290);
        _grid.Size     = new System.Drawing.Size(1190, 385);
        _grid.Anchor   = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right | AnchorStyles.Bottom;

        _ctxMenu     = new ContextMenuStrip();
        _menuBulkAdd = new ToolStripMenuItem("➕  Добавить в Массовые операции");
        _ctxMenu.Items.Add(_menuBulkAdd);
        _grid.ContextMenuStrip = _ctxMenu;

        Controls.AddRange(new Control[]
        {
            lblDomains, _clbDomains, lblFio, _txtFio,
            _btnLoadFile, _btnClearList,
            panFilters, panFields,
            _btnFind, _btnExport, _btnClear, _lblCount, _grid
        });

        ResumeLayout(false);
    }

    private Panel _panFields = null!;
}
