// <auto-generated/>
#nullable enable
using System.Drawing;
using System.Windows.Forms;
using ADManager.Helpers;

namespace ADManager.Tabs;

partial class Tab7_SearchByOU
{
    private System.ComponentModel.IContainer? components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    private Button _btnFindOU = null!;
    private Button _btnShow   = null!;
    private Button _btnExport = null!;
    private Panel  _panFields = null!;

    private void InitializeComponent()
    {
        this.Size          = new System.Drawing.Size(1200, 680);
        this.AutoScaleMode = AutoScaleMode.Font;
        BackColor = Color.FromArgb(240, 242, 245);
        SuspendLayout();

        // ── Строка 1: домен + поиск OU ──────────────────────────
        var lblDomain = UiFactory.MakeLabel("Домен:");
        lblDomain.Location = new Point(8, 6);

        _cbDomain = new ComboBox();
        _cbDomain.DropDownStyle = ComboBoxStyle.DropDownList;
        _cbDomain.Size          = new Size(220, 22);
        _cbDomain.Location      = new Point(8, 26);

        var lblOuSearch = UiFactory.MakeLabel("Поиск OU по названию:");
        lblOuSearch.Location = new Point(240, 6);

        _txtSearch = UiFactory.MakeTextBox("Введите название OU...", 300);
        _txtSearch.Location = new Point(240, 26);

        _btnFindOU = UiFactory.MakeActionButton("Найти OU", 110);
        _btnFindOU.Location = new Point(550, 24);

        // ── ListBox найденных OU ─────────────────────────────────
        var lblOuList = UiFactory.MakeLabel("Найденные OU (выберите одну):");
        lblOuList.Location = new Point(8, 54);

        _lbResults = new ListBox();
        _lbResults.Location            = new Point(8, 74);
        _lbResults.Size                = new Size(980, 110);
        _lbResults.HorizontalScrollbar = true;
        _lbResults.Font                = new Font("Consolas", 8.5f);
        _lbResults.Anchor              = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;

        // ── Фильтры ──────────────────────────────────────────────
        var panFilters = new Panel();
        panFilters.Location    = new Point(5, 192);
        panFilters.Size        = new Size(980, 28);
        panFilters.BackColor   = Color.FromArgb(230, 232, 238);
        panFilters.BorderStyle = BorderStyle.FixedSingle;

        var lblFHead = new Label();
        lblFHead.Text     = "Фильтры поиска:";
        lblFHead.Location = new Point(5, 6);
        lblFHead.AutoSize = true;
        lblFHead.Font     = new Font("Segoe UI", 8.5f);

        _chkActiveOnly = new CheckBox();
        _chkActiveOnly.Text      = "Только активные УЗ";
        _chkActiveOnly.Location  = new Point(120, 5);
        _chkActiveOnly.Size      = new Size(160, 20);
        _chkActiveOnly.Checked   = true;
        _chkActiveOnly.ForeColor = Color.FromArgb(30, 120, 50);

        _chkSubtree = new CheckBox();
        _chkSubtree.Text     = "Включая вложенные OU";
        _chkSubtree.Location = new Point(290, 5);
        _chkSubtree.Size     = new Size(180, 20);
        _chkSubtree.Checked  = true;

        panFilters.Controls.AddRange(new Control[] { lblFHead, _chkActiveOnly, _chkSubtree });

        // ── Поля для выгрузки (чекбоксы строятся в WireEvents) ──
        var panFields = new Panel();
        panFields.Location    = new Point(5, 224);
        panFields.Size        = new Size(980, 56);
        panFields.BackColor   = Color.FromArgb(230, 232, 238);
        panFields.BorderStyle = BorderStyle.FixedSingle;

        var lblFlds = new Label();
        lblFlds.Text     = "Поля для выгрузки:";
        lblFlds.Location = new Point(5, 9);
        lblFlds.AutoSize = true;
        lblFlds.Font     = new Font("Segoe UI", 8.5f);

        panFields.Controls.Add(lblFlds);
        _panFields = panFields;

        // ── Кнопки / счётчик ─────────────────────────────────────
        _btnShow = UiFactory.MakeActionButton("Показать пользователей", 180);
        _btnShow.Location = new Point(5, 292);

        _btnExport = UiFactory.MakeExportButton();
        _btnExport.Location = new Point(195, 292);

        _lblCount = new Label();
        _lblCount.Location  = new Point(330, 296);
        _lblCount.AutoSize  = true;
        _lblCount.ForeColor = Color.FromArgb(50, 100, 200);
        _lblCount.Font      = new Font("Segoe UI", 9f, FontStyle.Bold);

        _grid = UiFactory.MakeGrid();
        _grid.Location = new Point(5, 327);
        _grid.Size     = new System.Drawing.Size(1190, 348);
        _grid.Anchor   = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right | AnchorStyles.Bottom;

        Controls.AddRange(new Control[]
        {
            lblDomain, _cbDomain, lblOuSearch, _txtSearch, _btnFindOU,
            lblOuList, _lbResults, panFilters, panFields,
            _btnShow, _btnExport, _lblCount, _grid
        });

        ResumeLayout(false);
    }
}
