// <auto-generated/>
#nullable enable
namespace ADManager.Tabs;

partial class Tab_CreateUser
{
    private System.ComponentModel.IContainer? components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        SuspendLayout();
        AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
        AutoScaleMode       = System.Windows.Forms.AutoScaleMode.Font;
        Name                = "Tab_CreateUser";
        Size                = new System.Drawing.Size(1236, 547);
        ResumeLayout(false);
    }
}
