// <auto-generated/>
#nullable enable
using System.Drawing;
using System.Windows.Forms;
using ADManager.Helpers;

namespace ADManager.Tabs;

partial class Tab_BulkOperations
{
    private System.ComponentModel.IContainer? components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    // Fields zone
    private CheckBox _chkPosition    = null!;
    private TextBox  _txtPosition    = null!;
    private CheckBox _chkDepartment  = null!;
    private TextBox  _txtDepartment  = null!;
    private CheckBox _chkManager     = null!;
    private TextBox  _txtManager     = null!;
    private Button   _btnFindManager        = null!;
    private Button   _btnFindSubordinates   = null!;
    private Label    _lblOU          = null!;
    private CheckBox _chkOU          = null!;
    private TextBox  _txtOU          = null!;
    private Button   _btnOUInfo      = null!;
    private Label    _lblNote        = null!;

    // Buttons zone
    private Button   _btnDelete    = null!;
    private Button   _btnRun       = null!;
    private CheckBox _chkShowAll   = null!;
    private Button   _btnInfo      = null!;
    private Label    _lblUserCount = null!;

    // Grid
    private DataGridView _grid = null!;

    private void InitializeComponent()
    {
        AutoScaleMode = AutoScaleMode.Font;
        BackColor     = Color.FromArgb(240, 242, 245);
        SuspendLayout();

        // ── Fields panel ─────────────────────────────────────────
        var pnlFields = new Panel
        {
            Dock      = DockStyle.Top,
            Height    = 110,
            BackColor = Color.FromArgb(228, 230, 236)
        };

        // Row 1 (y=10): Position, Department, Manager, Find
        // txt_Position и txt_Department — одинаковой ширины (284px),
        // txt_Department заканчивается там же, где по умолчанию заканчивается столбец Руководитель (x=625)
        _chkPosition = new CheckBox
        {
            Location = new Point(8, 12),
            Size     = new Size(18, 18),
            Text     = ""
        };
        _txtPosition = new TextBox
        {
            Location        = new Point(28, 10),
            Size            = new Size(284, 24),
            PlaceholderText = "Изменить Должность",
            Font            = new Font("Segoe UI", 9f)
        };

        _chkDepartment = new CheckBox
        {
            Location = new Point(320, 12),
            Size     = new Size(18, 18),
            Text     = ""
        };
        _txtDepartment = new TextBox
        {
            Location        = new Point(340, 10),
            Size            = new Size(284, 24),   // ends at 624 ≈ Manager column right edge
            PlaceholderText = "Изменить Отдел",
            Font            = new Font("Segoe UI", 9f)
        };

        _chkManager = new CheckBox
        {
            Location = new Point(632, 12),
            Size     = new Size(18, 18),
            Text     = ""
        };
        _txtManager = new TextBox
        {
            Location        = new Point(652, 10),
            Size            = new Size(184, 24),
            PlaceholderText = "Изменить Руководителя",
            ReadOnly        = true,
            BackColor       = Color.FromArgb(235, 237, 242),
            Font            = new Font("Segoe UI", 9f)
        };

        _btnFindManager = new Button
        {
            Text      = "Найти",
            Location  = new Point(840, 10),
            Size      = new Size(65, 24),
            BackColor = Color.FromArgb(50, 55, 70),
            ForeColor = Color.White,
            FlatStyle = FlatStyle.Flat,
            Font      = new Font("Segoe UI", 8.5f, FontStyle.Bold)
        };
        _btnFindManager.FlatAppearance.BorderSize = 0;

        _btnFindSubordinates = new Button
        {
            Text      = "Найти подчинённых",
            Location  = new Point(912, 10),
            Size      = new Size(160, 24),
            BackColor = Color.FromArgb(120, 125, 140),
            ForeColor = Color.White,
            FlatStyle = FlatStyle.Flat,
            Font      = new Font("Segoe UI", 8.5f, FontStyle.Bold),
            Enabled   = false
        };
        _btnFindSubordinates.FlatAppearance.BorderSize = 0;

        // Row 2 label (y=40): label above OU field
        _lblOU = new Label
        {
            Text      = "OU для перемещения:",
            Location  = new Point(28, 40),
            AutoSize  = true,
            ForeColor = Color.FromArgb(90, 100, 120),
            Font      = new Font("Segoe UI", 8.5f)
        };

        // Row 2 controls (y=58): OU checkbox, OU field (ends at same x as _txtDepartment), Info button
        _chkOU = new CheckBox
        {
            Location = new Point(8, 60),
            Size     = new Size(18, 18),
            Text     = ""
        };
        _txtOU = new TextBox
        {
            Location        = new Point(28, 58),
            Size            = new Size(596, 24),   // ends at 624 = same as _txtDepartment right edge
            PlaceholderText = "Нажмите ⓘ для подсказки",
            ReadOnly        = true,
            BackColor       = Color.FromArgb(235, 237, 242),
            Font            = new Font("Segoe UI", 9f)
        };
        _btnOUInfo = new Button
        {
            Text      = "ⓘ",
            Location  = new Point(628, 54),
            Size      = new Size(36, 32),
            BackColor = Color.FromArgb(228, 230, 236),   // = pnlFields background
            ForeColor = Color.FromArgb(50, 100, 200),
            FlatStyle = FlatStyle.Flat,
            Font      = new Font("Segoe UI", 16f, FontStyle.Regular),
            Padding   = new Padding(0)
        };
        _btnOUInfo.FlatAppearance.BorderSize = 0;

        // Note (y=86)
        _lblNote = new Label
        {
            Text      = "Если отмеченные поля оставить пустыми, то при выполнении операции значения в этих полях сотрутся",
            Location  = new Point(8, 88),
            AutoSize  = true,
            ForeColor = Color.FromArgb(160, 100, 20),
            Font      = new Font("Segoe UI", 8f, FontStyle.Italic)
        };

        // Тонкий разделитель внизу зоны полей
        var pnlFieldsBorder = new Panel
        {
            Dock      = DockStyle.Bottom,
            Height    = 1,
            BackColor = Color.FromArgb(180, 185, 200)
        };

        pnlFields.Controls.AddRange(new Control[]
        {
            _chkPosition, _txtPosition,
            _chkDepartment, _txtDepartment,
            _chkManager, _txtManager, _btnFindManager,
            _lblOU, _chkOU, _txtOU, _btnOUInfo,
            _lblNote, pnlFieldsBorder,
            _btnFindSubordinates
        });

        // ── Buttons row ───────────────────────────────────────────
        var pnlButtons = new Panel
        {
            Dock      = DockStyle.Top,
            Height    = 40,
            BackColor = Color.FromArgb(240, 242, 245)
        };

        _btnDelete = new Button
        {
            Text      = "Удалить из списка",
            Location  = new Point(8, 4),
            Size      = new Size(150, 28),
            BackColor = Color.FromArgb(50, 55, 70),
            ForeColor = Color.White,
            FlatStyle = FlatStyle.Flat,
            Font      = new Font("Segoe UI", 9f, FontStyle.Bold)
        };
        _btnDelete.FlatAppearance.BorderSize = 0;

        _btnRun = new Button
        {
            Text      = "Запустить",
            Location  = new Point(166, 4),
            Size      = new Size(120, 28),
            BackColor = Color.FromArgb(120, 125, 140),
            ForeColor = Color.White,
            FlatStyle = FlatStyle.Flat,
            Font      = new Font("Segoe UI", 9f, FontStyle.Bold),
            Enabled   = false
        };
        _btnRun.FlatAppearance.BorderSize = 0;

        _chkShowAll = new CheckBox
        {
            Text     = "Показывать все столбцы",
            Location = new Point(298, 8),
            AutoSize = true,
            Checked  = false,
            Font     = new Font("Segoe UI", 9f)
        };

        _lblUserCount = new Label
        {
            Text      = "",
            Location  = new Point(480, 11),
            AutoSize  = true,
            ForeColor = Color.FromArgb(50, 100, 200),
            Font      = new Font("Segoe UI", 9f, FontStyle.Bold)
        };

        _btnInfo = new Button
        {
            Text      = "ⓘ",
            Location  = new Point(628, 2),
            Size      = new Size(36, 32),
            BackColor = Color.FromArgb(240, 242, 245),   // = pnlButtons background
            ForeColor = Color.FromArgb(50, 100, 200),
            FlatStyle = FlatStyle.Flat,
            Font      = new Font("Segoe UI", 16f, FontStyle.Regular),
            Padding   = new Padding(0)
        };
        _btnInfo.FlatAppearance.BorderSize = 0;

        pnlButtons.Controls.AddRange(new Control[]
        {
            _btnDelete, _btnRun, _chkShowAll, _lblUserCount, _btnInfo
        });

        // ── Grid ──────────────────────────────────────────────────
        _grid = UiFactory.MakeGrid();
        _grid.Dock           = DockStyle.Fill;
        _grid.SelectionMode  = DataGridViewSelectionMode.FullRowSelect;
        _grid.MultiSelect    = true;

        _grid.Columns.Add(new DataGridViewTextBoxColumn { Name = "Domain",      HeaderText = "Домен",          Width = 100 });
        _grid.Columns.Add(new DataGridViewTextBoxColumn { Name = "Login",       HeaderText = "Логин",          Width = 140 });
        _grid.Columns.Add(new DataGridViewTextBoxColumn { Name = "DisplayName", HeaderText = "Выводимое имя",  Width = 200 });
        _grid.Columns.Add(new DataGridViewTextBoxColumn { Name = "Position",    HeaderText = "Должность",      Width = 160, Visible = false });
        _grid.Columns.Add(new DataGridViewTextBoxColumn { Name = "Department",  HeaderText = "Отдел",          Width = 160, Visible = false });
        _grid.Columns.Add(new DataGridViewTextBoxColumn { Name = "Manager",     HeaderText = "Руководитель",   Width = 180 });
        _grid.Columns.Add(new DataGridViewTextBoxColumn { Name = "OUTarget",    HeaderText = "OU назначения",  Width = 260, Visible = false });
        _grid.Columns.Add(new DataGridViewTextBoxColumn { Name = "DN",          HeaderText = "DN", Visible = false, Width = 10 });

        Controls.Add(_grid);
        Controls.Add(pnlButtons);
        Controls.Add(pnlFields);

        ResumeLayout(false);
    }
}
